### ISSUE TITLE
Tracking issues from discord

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#10]
+ [x] better hovering tip
  + [x] #55
+ [x] Rename is broken. It either says that it's not supported, or it doesn't work, or only changes the symbol in one place.
+ [x] expression folding, currently we go three subtasks for first round of imrpoment:
  + [x] array folding
  + [x] dict folding
  + [x] func folding
+ [x] Note that you can make prerelease versions of vscode extensions. That way people can opt-in to more unstable builds
+ [x] #27
+ [ ] #82
+ [ ] #28

**Comment by Myriad-Dreamin** [comment]
Close and track rest problems in individual issues.
