### ISSUE TITLE
Milestone: v0.11.2

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#110]
- [ ] Investigate a memory exhausting bug.
- [ ] fix neovim configuration
- [x] https://github.com/Myriad-Dreamin/tinymist/issues/28
- [ ] autocompletion improvement
  - [ ] fix possibly wrong cursor offset from autocompletion request.
  - [x] fix some completion kind and may also PR the fix to typst-ide.
  - [ ] autocomplete even if no word boundary occurs after cursor (possibly same root cause as the first issue).
  - [ ] complete the named arguments with a colon with an extra space and may also PR the improvement to typst-ide.
  - [ ] improve completion kind and list by static analysis result.
