### ISSUE TITLE
Milestone: v0.11.3

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#138]
- [ ] Investigate a memory exhausting bug.
- [ ] fix neovim configuration
- [ ] autocompletion improvement
  - [ ] fix possibly wrong cursor offset from autocompletion request.
  - [ ] autocomplete even if no word boundary occurs after cursor (possibly same root cause as the first issue).
  - [ ] complete the named arguments with a colon with an extra space and may also PR the improvement to typst-ide.
  - [ ] improve completion kind and list by static analysis result.

**Comment by Coekjan** [comment]
I am suffering the memory/cpu exhausting bug...

My typst project has 50+ `.typ` file, organized into the final document using `#include file-path`.

```
.
├── info.typ           # <-- this file declares the `papers` function.
│                      # The `paper` function is used to include `papers/*.typ` into the final document
├── papers
│   ├── asplos16-hajj.typ
│   ├── ...
│   └── sosp23-wu.typ
├── reading-list.bib   # <-- bib file
├── reading-list.typ   # <-- the final document
├── README.md
├── requirements.typ   # <-- this file will be imported by `papers/*.typ` on necessity, providing dependencies
└── template.typ
```

Citing labels across files is very common in the project. When I open the `info.typ`, tinymist occupies 100% CPU for about 1~2 minutes and consumpts several GBs RAM (5+ ~ 15+ GB sometimes).

I am enchanted by typst and tinymist, but this bug is now so annoying me... I do some simple investigation on tinymist's cpu/memory usage, and the perf graph & dhat-json file are as follows. As I am not familiar with typst & tinymist source code, I cannot find out what is actually happening behind the exhaustion.

When I look into this issues, I find you, tinymist's author, are also investigating something like this. Hope my information can be helpful for your investigation.

![image](https://github.com/Myriad-Dreamin/tinymist/assets/69834864/1ad8cc04-68b8-4848-b00a-390c61f242da)
![image](https://github.com/Myriad-Dreamin/tinymist/assets/69834864/7f5beb3a-e26f-48e0-af8a-4def1e15624f)

[perf.tar.gz](https://github.com/Myriad-Dreamin/tinymist/files/14862303/perf.tar.gz)
[dhat-heap.json](https://github.com/Myriad-Dreamin/tinymist/files/14862224/dhat-heap.json)

**Comment by Myriad-Dreamin** [comment]
Hi, I have read the dhat-heap and figure out the reason: there are too many cache holding for big typst projects. This bad case could be mitigated by reduce cache by smaller steps, but may slow down the lsp. 

https://github.com/Myriad-Dreamin/tinymist/blob/1c5c6bd9292478443e26bcb035c9b47bed419860/crates/tinymist/src/actor/typ_server.rs#L375

If you would like to do, you can explore the following operations to help me debug your the big project:
+ turn on/off inlay hints and then open the `info.typ`.

  As I find that inlay hints could trigger the compilation many times.

+ `ctrl` + `shift` + `p` and run the vscode command: `Typst Clear Cache`.
  + after you opening the `info.typ`.
  + keystroke a single word in the document and rerun the clear cache command.
  + keystroke two or more single word in the document and rerun the clear cache command.

  Current the cold cache are totally evicted only if behind your 30 keystrokes, which is not good for running big projects.

The memory consumption statistics of these operations could help me find a good balance.

Also could you send me the channel log related to the slow loading the project?

**Comment by Myriad-Dreamin** [comment]
The above operations to explore and the following are not requests but optional. Could you also send me the papers and the information, which can help me do optimization on analysis on function calls, which is likely to be memory consuming.

**Comment by Myriad-Dreamin** [comment]
The way to turn off inlay hint **globally**, that is in your user setting:

![image](https://github.com/Myriad-Dreamin/tinymist/assets/35292584/02476ce2-b8d3-4a6a-863b-0d0fb0c2116c)

**Comment by Myriad-Dreamin** [comment]
> > * turn on/off inlay hints and then open the `info.typ`.
> >   As I find that inlay hints could trigger the compilation many times.
> 
> I turned off the inlay hints just now, but the exhaustion seems not to be mitigated.
> 
> EDIT: Oh, sorry, the exhaustion is almost solved by turning off the inlay hints.

Sorry that bother you, you can turn off the inlay hints by setting it in your local workspace's configuration `.vscode/settings.json`.

The cost to inlay hints is not a problem on most projects, and so please turn off it only in your the big project, and not for other projects (and please note that it will also turn off the inlay hints for other languages).

I will also let you know after I believing it not a problem to big projects.
