### ISSUE TITLE
Milestone: v0.11.1

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#56]
I use a todo list format to put down what I will do for v0.11.1 publish.
+ [x] #24
+ [x] #38
+ [x] #55
+ [x] perform memory/heap usage profiling and optimization.
  + [x] #95
+ [x] create `editor/neovim` for maintaining configuration for neovim users.
+ [x] write README.md for neovim users for guidance.

These issues are highlighted but I may not work on them until next publish.
+ #14
+ #28
