### ISSUE TITLE
Tracking issues from Discord 2

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/tinymist#83]
+ [x] Can't you also accommodate the Neovim's config file(s) in your repo?
+ fix neovim configuration: https://github.com/neovim/nvim-lspconfig/pull/3075#discussion_r1527487071
+ [x] Maybe I'll give you the file in question, 70% sure it's specific to this one (either unique to this file or the effect is over amplified on this one)
+ [x] if I have a folder open that is not the one that my typ file is in, then the lsp does not work at all
